# Generated by Django 2.1.7 on 2022-12-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player_id', models.IntegerField(verbose_name='Player_id')),
                ('Name', models.CharField(max_length=255, verbose_name='Name')),
                ('Position', models.IntegerField(verbose_name='Position')),
                ('Ranking_position', models.IntegerField(verbose_name='Ranking_position')),
                ('Matches_played', models.IntegerField(verbose_name='Matches_played')),
                ('Matches_played_percentage', models.FloatField(verbose_name='Matches_played')),
                ('Usually_starting', models.IntegerField(verbose_name='Usually_starting')),
                ('Goals_OR_saved_penalties', models.IntegerField(verbose_name='Goals_OR_saved_penalties')),
                ('Penalty_goals_OR_clean_sheets', models.IntegerField(verbose_name='Penalty_goals_OR_clean_sheets')),
                ('Assists', models.IntegerField(verbose_name='Assists')),
                ('Yellow_cards', models.IntegerField(verbose_name='Yellow_cards')),
                ('Red_cards', models.IntegerField(verbose_name='Red_cards')),
                ('Points', models.IntegerField(verbose_name='Points')),
                ('Average_points', models.FloatField(verbose_name='Average_points')),
                ('Current_price', models.BigIntegerField(verbose_name='Current_price')),
                ('Max_price', models.BigIntegerField(verbose_name='Max_price')),
                ('Min_price', models.BigIntegerField(verbose_name='Min_price')),
                ('Average_points_last_5_games', models.FloatField(verbose_name='Average_points_last_5_games')),
                ('J_minus4', models.IntegerField(verbose_name='J_minus4')),
                ('J_minus3', models.IntegerField(verbose_name='J_minus3')),
                ('J_minus2', models.IntegerField(verbose_name='J_minus2')),
                ('J_minus1', models.IntegerField(verbose_name='J_minus1')),
                ('J_actual', models.IntegerField(verbose_name='J_actual')),
            ],
        ),
    ]
